name: DSL logs and checks

on:
  pull_request:
    paths:
      - 'jenkins-scripts/dsl/**'

jobs:
  xml_generation:
    runs-on: ubuntu-latest
    name: Generate XML config from DSL
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Download and setup job dsl jar
        run: ./jenkins-scripts/dsl/tools/setup_local_generation.bash
      - name: Generate XML files
        run: |
          # simulate token for brew_release
          sudo mkdir -p /var/lib/jenkins/ && sudo touch /var/lib/jenkins/remote_token
          sudo chown -R ${USER} /var/lib/jenkins
          pushd jenkins-scripts/dsl
          WRITE_JOB_LOG=1 java -jar tools/jobdsl.jar *.dsl
          find logs/* -exec sort {} -o {} \;
          git diff
          popd
      - name: Update and commit logs generated
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: jenkins-scripts/dsl/logs/
          commit_author: 'GitHub Bot in release-tools <github-actions-bot@local>'
          commit_message: 'Automated change: update logs'
          commit_options: '--no-verify --signoff'
          commit_user_email: github-actions-bot@local
      - name: Archive DSL configuration
        uses: actions/upload-artifact@v3
        with:
          name: dsl-dir
          path: |
            jenkins-scripts/dsl

  xml_checks:
    needs: xml_generation
    runs-on: ubuntu-latest
    name: Checks for generated configuration
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: dsl-dir
      - run: |
          ls -R
          /bin/bash ./dsl_checks.bash

  xml_diff:
    needs: xml_checks
    runs-on: ubuntu-latest
    name: Export XML generated configuration for diff
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: dsl-dir
      - run: |
          # export files for later diff
          mkdir /tmp/pr_xml_configuration
          # sort all generated log files
          mv *.xml /tmp/pr_xml_configuration/
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0
      - name: Download and setup job dsl jar
        run: ./jenkins-scripts/dsl/tools/setup_local_generation.bash
      - name: Generate master branch DSL files
        run: |
          pushd jenkins-scripts/dsl
          WRITE_JOB_LOG=1 java -jar tools/jobdsl.jar *.dsl
          mv *.xml /tmp/current_xml_configuration/
          popd
      - name: Generating diffs
        run: |
          # somehow the Jenkins views changed the portlet_ id on every run.
          diff -qr -I '.*<id>dashboard_portlet_.*</id>.*' /tmp/current_xml_configuration /tmp/pr_xml_configuration | sort > /tmp/xml_config_files_changed.diff || true
          diff -ur -I '.*<id>dashboard_portlet_.*</id>.*' /tmp/current_xml_configuration /tmp/pr_xml_configuration > /tmp/xml_config_content_changed.diff || true
      - name: Archive files changes
        uses: actions/upload-artifact@v3
        with:
          name: xml_config_files_changed
          path: /tmp/xml_config_files_changed.diff
      - name: Archive content changes
        uses: actions/upload-artifact@v3
        with:
          name: xml_config_content_changed
          path: /tmp/xml_config_content_changed.diff
