name: DSL logs and checks

on:
  push:
    paths:
      - 'jenkins-scripts/dsl/**'

jobs:
  xml_generation:
    runs-on: ubuntu-latest
    name: Diff for DSL code
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Download and setup job dsl jar
        run: ./jenkins-scripts/dsl/tools/setup_local_generation.bash
      - name: Generate XML files
        run: |
          # simulate token for brew_release
          sudo mkdir -p /var/lib/jenkins/ && sudo touch /var/lib/jenkins/remote_token
          sudo chown -R ${USER} /var/lib/jenkins
          cd jenkins-scripts/dsl
          WRITE_JOB_LOG=1 java -jar tools/jobdsl.jar *.dsl

  xml_checks:
    needs: xml_generation
    runs-on: ubuntu-latest
    name: Generate configuration from DSL files
    steps:
      - name: Checks for generated configuration
        run: |
          cd jenkins-scripts/dsl
          ./dsl_checks.bash

  update_logs:
    needs: xml_checks
    runs-on: ubuntu-latest
    name: Update and commit logs generated
    steps:
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: logs/
          commit_author: GitHub Bot in release-tools
          commit_message: "Automated change: update logs"
          commit_options: '--no-verify --signoff'
          commit_user_email: github-actions-bot@local

  xml_diff:
    needs: xml_checks
    runs-on: ubuntu-latest
    name: Generate configuration from DSL files
    steps:
      - name: Export XML generated configuration for diff
        run: |
          cd jenkins-scripts/dsl
          # export files for later diff
          mkdir /tmp/pr_xml_configuration
          # sort all generated log files
          find logs/* -exec sort {} -o {} \;
          mv *.xml /tmp/pr_xml_configuration/
      - name: Generate master DSL files
        run: |
          git clean -f -e jobdsl.jar
          git checkout master
          cd jenkins-scripts/dsl
          WRITE_JOB_LOG=1 java -jar tools/jobdsl.jar *.dsl
          # sort jobs.txt
          sort jobs.txt -o jobs.txt
          mv *.xml /tmp/current_xml_configuration/
      - name: Generating diffs
        run: |
          # somehow the Jenkins views changed the portlet_ id on every run.
          diff -qr -I '.*<id>dashboard_portlet_.*</id>.*' /tmp/current_xml_configuration /tmp/pr_xml_configuration | sort > /tmp/xml_config_files_changed.diff || true
          diff -ur -I '.*<id>dashboard_portlet_.*</id>.*' /tmp/current_xml_configuration /tmp/pr_xml_configuration > /tmp/xml_config_content_changed.diff || true
      - name: Archive files changes
        uses: actions/upload-artifact@v3
        with:
          name: xml_config_files_changed
          path: /tmp/xml_config_files_changed.diff
      - name: Archive content changes
        uses: actions/upload-artifact@v3
        with:
          name: xml_config_content_changed
          path: /tmp/xml_config_content_changed.diff
