name: Main CI checks

on: push

jobs:
  dsl_ci:
    runs-on: ubuntu-latest
    name: Diff for DSL code
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run release.py script tests
        run: ./check_releasepy.bash
